package com.example

/**
 * Top 100 most common English phrasal verbs with formal and informal/colloquial usage.
 */
object PhrasalVerbsData {
    val verbs: List<PhrasalVerb> = listOf(
        PhrasalVerb(
            id = 1,
            verb = "Give up",
            summaryMeaning = "يستسلم / يقلع عن عادة أو محاولة",
            formalMeaning = "التنازل رسمياً عن حق، أو التراجع عن دعوى أو مسعى مؤسسي.",
            formalExample = "The company refused to give up its intellectual property rights in court.",
            formalExampleTranslation = "رفضت الشركة التنازل عن حقوق ملكيتها الفكرية في المحكمة.",
            informalMeaning = "الاستسلام والتوقف عن المحاولة بسبب الإحباط أو التعب.",
            informalExample = "I give up, this video game level is way too hard!",
            informalExampleTranslation = "أنا أستسلم، هذه المرحلة من لعبة الفيديو صعبة للغاية!"
        ),
        PhrasalVerb(
            id = 2,
            verb = "Look after",
            summaryMeaning = "يعتني بـ / يرعى شخصاً أو شيئاً",
            formalMeaning = "تولي المسؤولية الإشرافية أو القانونية لرعاية شخص أو حماية ممتلكات.",
            formalExample = "The appointed trustee will look after the minor's financial estate.",
            formalExampleTranslation = "سيتولى الوصيّ المعيَّن الإشراف على التركة المالية للقاصر.",
            informalMeaning = "الاعتناء بصديق، طفل، أو حيوان أليف أثناء الغياب.",
            informalExample = "Can you look after my dog while I run to the grocery store?",
            informalExampleTranslation = "هل يمكنك الاعتناء بكلبي بينما أذهب إلى البقالة سريعاً؟"
        ),
        PhrasalVerb(
            id = 3,
            verb = "Call off",
            summaryMeaning = "يلغي حدثاً أو اتفاقاً أو عملية",
            formalMeaning = "إلغاء رسمي لاجتماع دبلوماسي، صفقة تجارية أو حملة عسكرية.",
            formalExample = "The government decided to call off the bilateral summit due to political tensions.",
            formalExampleTranslation = "قررت الحكومة إلغاء القمة الثنائية رسمياً بسبب التوترات السياسية.",
            informalMeaning = "إلغاء موعد أو سهرة بين الأصدقاء في اللحظة الأخيرة.",
            informalExample = "We had to call off the barbecue party because of sudden rain.",
            informalExampleTranslation = "اضطررنا لإلغاء حفلة الشواء بسبب هطول المطر فجأة."
        ),
        PhrasalVerb(
            id = 4,
            verb = "Bring up",
            summaryMeaning = "يطرح موضوعاً للنقاش / يربي أطفالاً",
            formalMeaning = "طرح بند جديد في جدول أعمال رسمي للمداولة أو المراجعة.",
            formalExample = "The auditor promised to bring up the compliance discrepancy at the board meeting.",
            formalExampleTranslation = "تعهد المدقق بطرح التفاوت في الامتثال خلال اجتماع مجلس الإدارة.",
            informalMeaning = "فتح سيرة موضوع محرج أو ذكر ذكرى قديمة في محادثة.",
            informalExample = "Why did you have to bring up that embarrassing story in front of my friends?",
            informalExampleTranslation = "لماذا كان عليك فتح تلك السيرة المحرجة أمام أصدقائي؟"
        ),
        PhrasalVerb(
            id = 5,
            verb = "Carry on",
            summaryMeaning = "يواصل ويستمر / يتصرف بانفعال وصخب",
            formalMeaning = "مواصلة تنفيذ خطة عمل أو عمليات تجارية بعد انقطاع.",
            formalExample = "The enterprise will carry on international operations despite economic sanctions.",
            formalExampleTranslation = "ستواصل المؤسسة عملياتها الدولية على الرغم من العقوبات الاقتصادية.",
            informalMeaning = "المبالغة في الصراخ أو التذمر والتصرف بطريقة درامية.",
            informalExample = "Stop carrying on like that, it's just a tiny scratch!",
            informalExampleTranslation = "توقف عن الصراخ والتذمر هكذا، إنه مجرد خدش بسيط!"
        ),
        PhrasalVerb(
            id = 6,
            verb = "Find out",
            summaryMeaning = "يكتشف حقيقة أو معلومة",
            formalMeaning = "التحقق والاستكشاف من خلال تحقيقات منهجية أو تدقيق إحصائي.",
            formalExample = "The investigative committee sought to find out who authorized the budget deficit.",
            formalExampleTranslation = "سعت لجنة التحقيق إلى كشف وتحديد من صرّح بالعجز في الميزانية.",
            informalMeaning = "معرفة سر أو حقيقة بالصدفة من القيل والقال.",
            informalExample = "Wait until my parents find out I failed my driving test!",
            informalExampleTranslation = "انتظر فقط حتى يكتشف والداي أنني رسبت في اختبار القيادة!"
        ),
        PhrasalVerb(
            id = 7,
            verb = "Get along",
            summaryMeaning = "ينسجم ويتفاهم / يغادر المكان",
            formalMeaning = "الحفاظ على علاقات عمل مهنية وتوافق بناء بين فرق العمل.",
            formalExample = "Management praised the department's ability to get along and achieve project milestones.",
            formalExampleTranslation = "أشادت الإدارة بقدرة القسم على التوافق والانسجام لتحقيق أهداف المشروع.",
            informalMeaning = "التآلف والود بين الأصدقاء، أو الحث على المغادرة ('I must get along').",
            informalExample = "My new roommate and I get along like best friends.",
            informalExampleTranslation = "أنا وزميلي الجديد في السكن ننسجم ونتعامل كأعز صديقين."
        ),
        PhrasalVerb(
            id = 8,
            verb = "Give away",
            summaryMeaning = "يتبرع مجاناً / يفشي سراً بالخطأ",
            formalMeaning = "التنازل الخيري عن أصول أو توزيع جوائز ومكافآت في حفل رسمي.",
            formalExample = "The charitable foundation will give away educational grants to qualified applicants.",
            formalExampleTranslation = "ستمنح المؤسسة الخيرية منحاً تعليمية للمتقدمين المؤهلين.",
            informalMeaning = "حرق أحداث فيلم أو إفشاء مفاجأة حفلة بالخطأ.",
            informalExample = "Don't give away the ending of the movie, I haven't watched it yet!",
            informalExampleTranslation = "لا تحرق نهاية الفيلم، فأنا لم أشاهده بعد!"
        ),
        PhrasalVerb(
            id = 9,
            verb = "Look forward to",
            summaryMeaning = "يتطلع بشوق وحماس لمناسبة قادمة",
            formalMeaning = "عبارة مهنية شائعة لختام المراسلات وتوقع التعاون المستقبلي.",
            formalExample = "We look forward to establishing a fruitful partnership with your organization.",
            formalExampleTranslation = "نتطلع باهتمام إلى إقامة شراكة مثمرة وناجحة مع منظمتكم.",
            informalMeaning = "الشوق الشديد لعطلة نهاية الأسبوع أو لقاء الأصدقاء.",
            informalExample = "I'm really looking forward to the weekend road trip!",
            informalExampleTranslation = "أنا متشوق جداً لرحلة السيارة في عطلة نهاية الأسبوع!"
        ),
        PhrasalVerb(
            id = 10,
            verb = "Put off",
            summaryMeaning = "يؤجل موعداً / ينفر ويثير الاشمئزاز",
            formalMeaning = "تأجيل رسمي لموعد جلسة محكمة أو توقيع اتفاقية.",
            formalExample = "The hearing was put off until further forensic evidence could be collected.",
            formalExampleTranslation = "تم تأجيل جلسة الاستماع حتى يتم جمع المزيد من الأدلة الجنائية.",
            informalMeaning = "الشعور بالنفور والاشمئزاز من تصرف أو طعام معين.",
            informalExample = "The smell of that fish totally put me off eating lunch.",
            informalExampleTranslation = "رائحة ذلك السمك جعلتني أنفر تماماً من تناول الغداء."
        ),
        PhrasalVerb(
            id = 11,
            verb = "Run into",
            summaryMeaning = "يصادف شخصاً / يواجه مشكلات أو عوائق",
            formalMeaning = "مواجهة غير متوقعة لعوائق بيروقراطية أو عجز مالي في مشروع.",
            formalExample = "The infrastructure initiative ran into severe regulatory hurdles.",
            formalExampleTranslation = "واجهت مبادرة البنية التحتية عقبات تنظيمية ورقابية شديدة.",
            informalMeaning = "مقابلة صديق قديم بالصدفة في السوق أو الشارع.",
            informalExample = "Guess who I ran into at the mall today? My old school buddy!",
            informalExampleTranslation = "خمّن من قابلت صدفة في المركز التجاري اليوم؟ صديق دراستي القديم!"
        ),
        PhrasalVerb(
            id = 12,
            verb = "Set up",
            summaryMeaning = "يؤسس شركة / يركّب أجهزة / يوقع بشخص فخاً",
            formalMeaning = "تأسيس كيان تجاري أو تنظيم هيكل إداري جديد.",
            formalExample = "The executives decided to set up a regional subsidiary in Dubai.",
            formalExampleTranslation = "قرر المسؤولون التنفيذيون تأسيس شركة فرعية إقليمية في دبي.",
            informalMeaning = "تدبير فخ أو توريط شخص في موقف محرج أو غير قانوني.",
            informalExample = "He claims he was innocent and that his coworkers set him up.",
            informalExampleTranslation = "يدعي أنه بريء وأن زملاءه في العمل نصبوا له فخاً وورطوه."
        ),
        PhrasalVerb(
            id = 13,
            verb = "Take off",
            summaryMeaning = "تقلع الطائرة / يخلع الملابس / يحقق نجاحاً مفاجئاً",
            formalMeaning = "المغادرة الجوية للرحلات، أو النمو الاقتصادي المتسارع للمؤسسة.",
            formalExample = "Commercial aircraft must comply with safety protocols before they take off.",
            formalExampleTranslation = "يجب أن تمتثل الطائرات التجارية لبروتوكولات السلامة قبل أن تقلع.",
            informalMeaning = "المغادرة على عجل وبشكل مفاجئ، أو انطلاق شهرة شيء بسرعة.",
            informalExample = "Sorry guys, it's getting late so I gotta take off now.",
            informalExampleTranslation = "معذرة يا شباب، لقد تأخر الوقت وعليّ المغادرة مسرعاً الآن."
        ),
        PhrasalVerb(
            id = 14,
            verb = "Turn down",
            summaryMeaning = "يرفض عرضاً أو طلباً / يخفض الصوت",
            formalMeaning = "الرفض الرسمي لطلب منحة أو عطاء تجاري أو ترشيح.",
            formalExample = "The admissions committee had to turn down numerous overseas applications.",
            formalExampleTranslation = "اضطرت لجنة القبول إلى رفض العديد من طلبات التقديم الخارجية رسمياً.",
            informalMeaning = "تخفيض صوت الموسيقى أو التلفاز.",
            informalExample = "Can you please turn down the music? I'm trying to sleep.",
            informalExampleTranslation = "هل يمكنك خفض صوت الموسيقى من فضلك؟ أحاول أن أنام."
        ),
        PhrasalVerb(
            id = 15,
            verb = "Come across",
            summaryMeaning = "يعثر بالصدفة / يترك انطباعاً لدى الآخرين",
            formalMeaning = "ترك انطباع محدد عن الشخصية أو النوايا خلال مقابلة رسمية.",
            formalExample = "The candidate came across as extremely composed and competent during the hearing.",
            formalExampleTranslation = "ترك المرشح انطباعاً بأنه واثق للغاية وكفؤ أثناء جلسة المقابلة.",
            informalMeaning = "العثور على غرض قديم أو منسي أثناء تنظيف الغرفة.",
            informalExample = "I came across my childhood diary while clearing out the attic.",
            informalExampleTranslation = "عثرت بالصدفة على مذكرات طفولتي أثناء تنظيف العلية."
        ),
        PhrasalVerb(
            id = 16,
            verb = "Break down",
            summaryMeaning = "يتعطل ميكانيكياً / يحلل البيانات / ينهار عاطفياً",
            formalMeaning = "تقسيم وتحليل إحصائي معقد لبيانات الميزانية أو التقرير.",
            formalExample = "The financial analyst will break down the annual expenditure into quarterly segments.",
            formalExampleTranslation = "سيقوم المحلل المالي بتفكيك وتحليل النفقات السنوية إلى أقسام ربع سنوية.",
            informalMeaning = "تعطل السيارة في الطريق، أو البكاء والانهيار بعد ضغط نفسي.",
            informalExample = "My old beat-up car broke down right in the middle of traffic.",
            informalExampleTranslation = "تعطلت سيارتي القديمة فجأة في وسط زحام المرور."
        ),
        PhrasalVerb(
            id = 17,
            verb = "Look up",
            summaryMeaning = "يبحث عن معلومة في مرجع / تتحسن الأوضاع",
            formalMeaning = "الرجوع إلى مصادر ومراجع موثوقة للتحقق من بند قانوني أو لغوي.",
            formalExample = "Researchers should look up precedent legal rulings in the official federal archives.",
            formalExampleTranslation = "ينبغي للباحثين مراجعة الأحكام القانونية السابقة في الأرشيف الفيدرالي الرسمي.",
            informalMeaning = "تحسن الظروف المعيشية والمالية بعد فترة صعبة.",
            informalExample = "Things were tough last month, but now life is finally looking up!",
            informalExampleTranslation = "كانت الأمور صعبة الشهر الماضي، لكن الأوضاع بدأت تتحسن أخيراً!"
        ),
        PhrasalVerb(
            id = 18,
            verb = "Make up",
            summaryMeaning = "يؤلف عذراً / يتصالح بعد خلاف / يضع مكياجاً",
            formalMeaning = "تشكيل النسبة الإجمالية لتركيبة مجتمعية أو ميزانية.",
            formalExample = "Renewable energy sources make up over thirty percent of the national grid.",
            formalExampleTranslation = "تشكل مصادر الطاقة المتجددة أكثر من ثلاثين بالمائة من الشبكة الوطنية.",
            informalMeaning = "تلفيق كذبة أو عذر لتبرير التأخر، أو التصالح بعد شجار.",
            informalExample = "He made up a crazy story about an alien abduction just to excuse his absence.",
            informalExampleTranslation = "ألّف قصة خيالية عن اختطاف فضائيين فقط ليبرر غيابه."
        ),
        PhrasalVerb(
            id = 19,
            verb = "Figure out",
            summaryMeaning = "يفهم ويستوعب / يحل مسألة معقدة",
            formalMeaning = "استنتاج رياضي أو منطقي لحل معضلة استراتيجية في العمليات.",
            formalExample = "The engineers had to figure out the structural load calculations before construction.",
            formalExampleTranslation = "كان على المهندسين حساب واستنتاج حمولة الهيكل بدقة قبل بدء البناء.",
            informalMeaning = "فهم تصرفات شخص غريبة أو حل لغز يومي.",
            informalExample = "I can never figure out why my cat stares at the blank wall for hours.",
            informalExampleTranslation = "لا أستطيع أبداً أن أفهم لماذا تحدق قطتي في الجدار الفارغ لساعات."
        ),
        PhrasalVerb(
            id = 20,
            verb = "Hold on",
            summaryMeaning = "ينتظر لحظة / يتمسك بشيء بقوة",
            formalMeaning = "التمسك بالموقف التفاوضي أو تعليق المكالمة الرسمية للتحويل.",
            formalExample = "Please hold on while I transfer your inquiry to the legal advisory division.",
            formalExampleTranslation = "يرجى الانتظار بينما أقوم بتحويل استفساركم إلى قسم الاستشارات القانونية.",
            informalMeaning = "التوقف السريع في الكلام للتحقق من أمر ما.",
            informalExample = "Hold on a second, did you just say you won the lottery?!",
            informalExampleTranslation = "تمهل لحظة واحدة، هل قلت للتو أنك ربحت اليانصيب؟!"
        ),
        PhrasalVerb(
            id = 21,
            verb = "Keep up with",
            summaryMeaning = "يواكب التطورات / يماشي نفس السرعة",
            formalMeaning = "مواكبة التغيرات التنظيمية والتشريعية في قطاع الصناعة.",
            formalExample = "Corporations must continuously innovate to keep up with stringent market regulations.",
            formalExampleTranslation = "يجب على الشركات أن تبتكر باستمرار لمواكبة اللوائح التنظيمية الصارمة في السوق.",
            informalMeaning = "متابعة أحدث أخبار المشاهير وصيحات الموضة.",
            informalExample = "I can't keep up with all these new slang words teenagers use nowadays!",
            informalExampleTranslation = "لا أستطيع مواكبة كل هذه الكلمات العامية الجديدة التي يستخدمها المراهقون اليوم!"
        ),
        PhrasalVerb(
            id = 22,
            verb = "Pass out",
            summaryMeaning = "يغمى عليه / يوزع أوراقاً ومستندات",
            formalMeaning = "توزيع رسمي للوثائق، المواد التدريبية أو شهادات التخرج.",
            formalExample = "The proctor will pass out the standardized examination booklets precisely at nine.",
            formalExampleTranslation = "سيقوم المراقب بتوزيع كتيبات الاختبار المعياري في تمام التاسعة تماماً.",
            informalMeaning = "الإغماء وفقدان الوعي من شدة الإجهاد أو السهر.",
            informalExample = "After pulling an all-nighter for finals, he passed out on the sofa.",
            informalExampleTranslation = "بعد السهر طوال الليل للمذاكرة، غاب عن الوعي ونام على الأريكة من التعب."
        ),
        PhrasalVerb(
            id = 23,
            verb = "Run out of",
            summaryMeaning = "ينفد مخزونه من شيء بالكامل",
            formalMeaning = "استنفاد الاحتياطي المالي أو الموارد التمويلية المخصصة للمشروع.",
            formalExample = "The non-governmental organization ran out of humanitarian relief supplies.",
            formalExampleTranslation = "استنفدت المنظمة غير الحكومية إمدادات الإغاثة الإنسانية المخصصة لديها.",
            informalMeaning = "نفاد القهوة أو شحن بطارية الهاتف الذكي.",
            informalExample = "My phone just ran out of battery, can I borrow your charger?",
            informalExampleTranslation = "نفد شحن بطارية هاتفي للتو، هل يمكنني استعارة شاحنك؟"
        ),
        PhrasalVerb(
            id = 24,
            verb = "Stand out",
            summaryMeaning = "يبرز ويتفوق / يكون مميزاً وملفتاً",
            formalMeaning = "التميز المهني أو التفرد الاستراتيجي لمنتج بين المنافسين.",
            formalExample = "Her extensive leadership background made her application stand out among candidates.",
            formalExampleTranslation = "جعلتها خبرتها القيادية الواسعة تبرز وتتفوق بين ملفات المرشحين للمنصب.",
            informalMeaning = "لفت الأنظار بارتداء ألوان زاهية وغريبة وسط الحشد.",
            informalExample = "Wearing a neon pink jacket made him stand out in the crowded club.",
            informalExampleTranslation = "ارتداؤه سترة وردية فاقعة جعله يلفت الأنظار وسط الحشد في النادي."
        ),
        PhrasalVerb(
            id = 25,
            verb = "Work out",
            summaryMeaning = "يتدرب رياضياً / تنجح الأمور وتُحل",
            formalMeaning = "صياغة واستنباط حلول توافقية لبنود عقد أو اتفاقية عمل.",
            formalExample = "Legal counsel worked out an amicable settlement between both dispute parties.",
            formalExampleTranslation = "توصل المستشار القانوني إلى تسوية ودية وتوافقية بين طرفي النزاع.",
            informalMeaning = "ممارسة التمارين في الصالة الرياضية (الجيم).",
            informalExample = "I'm heading to the gym to work out and lift some weights.",
            informalExampleTranslation = "أنا ذاهب إلى الجيم لأتدرب رياضياً وأرفع بعض الأثقال."
        ),
        PhrasalVerb(
            id = 26,
            verb = "Back down",
            summaryMeaning = "يتراجع عن موقف أو تهديد",
            formalMeaning = "التراجع الدبلوماسي أو التنازل عن شروط تفاوضية تحت الضغط الدولي.",
            formalExample = "Neither negotiation party was willing to back down on territorial boundaries.",
            formalExampleTranslation = "لم يكن أي من طرفي المفاوضات مستعداً للتراجع عن الحدود الإقليمية.",
            informalMeaning = "الانسحاب من جدال بعد إدراك الخطأ أو الخوف من العواقب.",
            informalExample = "He tried to start a fight, but backed down once he saw my older brother.",
            informalExampleTranslation = "حاول أن يبدأ شجاراً، لكنه تراجع بسرعة حين رأى أخي الأكبر."
        ),
        PhrasalVerb(
            id = 27,
            verb = "Blow up",
            summaryMeaning = "ينفجر / يغضب بشدة / ينتشر بسرعة فائقة",
            formalMeaning = "انفجار مادي أو تصاعد حاد ومفاجئ في التوترات الجيوسياسية.",
            formalExample = "Military intelligence warned that regional conflict could blow up unexpectedly.",
            formalExampleTranslation = "حذرت الاستخبارات العسكرية من أن النزاع الإقليمي قد ينفجر بشكل غير متوقع.",
            informalMeaning = "فقدان الأعصاب والصراخ، أو انتشار منشور انتشاراً فيروسياً.",
            informalExample = "Her TikTok dance video blew up overnight and got ten million views!",
            informalExampleTranslation = "فيديو رقصتها على تيك توك ضرب وانتشر بقوة بين عشية وضحاها وحصد 10 ملايين مشاهدة!"
        ),
        PhrasalVerb(
            id = 28,
            verb = "Break in",
            summaryMeaning = "يقتحم مكاناً / يدرب شخصاً / يلين حذاءً جديداً",
            formalMeaning = "اقتحام غير مشروع لمقر محمي أو منشأة حكومية خاضعة للحراسة.",
            formalExample = "Perpetrators attempted to break in through the embassy rear security portal.",
            formalExampleTranslation = "حاول الجناة اقتحام البوابة الأمنية الخلفية للسفارة بطريقة غير مشروعة.",
            informalMeaning = "المشي بحذاء جلدي جديد حتى يصبح مريحاً ولطيفاً على القدم.",
            informalExample = "I need to break in these new leather boots before our hiking trip.",
            informalExampleTranslation = "أحتاج إلى تليين هذا الحذاء الجلدي الجديد قبل الذهاب في رحلة المشي الجبلي."
        ),
        PhrasalVerb(
            id = 29,
            verb = "Break out",
            summaryMeaning = "يندلع حريق أو حرب / يهرب من سجن / يظهر طفح جلدي",
            formalMeaning = "اندلاع نزاع مسلح أو انتشار مفاجئ لوباء صحي عالمي.",
            formalExample = "International monitors feared that civil unrest would break out across the capital.",
            formalExampleTranslation = "تخوف المراقبون الدوليون من اندلاع اضطرابات مدنية واسعة في العاصمة.",
            informalMeaning = "ظهور حب الشباب أو البثور فجأة في الوجه قبل موعد مهم.",
            informalExample = "My face broke out with pimples the night before my graduation ceremony.",
            informalExampleTranslation = "ظهرت البثور في وجهي فجأة في الليلة التي سبقت حفل تخرجي."
        ),
        PhrasalVerb(
            id = 30,
            verb = "Break up",
            summaryMeaning = "ينفصل عاطفياً / يفكك احتكاراً / يتقطع الصوت",
            formalMeaning = "تفكيك احتكار تجاري أو حل هيئة تشريعية أو شراكة مؤسسية.",
            formalExample = "The antitrust regulator moved to break up the telecommunications monopoly.",
            formalExampleTranslation = "تحرك جهاز مكافحة الاحتكار لتفكيك وإلغاء احتكار قطاع الاتصالات.",
            informalMeaning = "إنهاء علاقة حب، أو تقطع صوت الاتصال عبر الهاتف.",
            informalExample = "You're breaking up! Move near the window, the cell signal is weak.",
            informalExampleTranslation = "صوتك يتقطع! تحرك بجوار النافذة، إشارة الهاتف ضعيفة هنا."
        ),
        PhrasalVerb(
            id = 31,
            verb = "Bring about",
            summaryMeaning = "يُحدث ويُسبّب تغييراً أو نتيجة",
            formalMeaning = "إحداث تحول مؤسسي كبير أو إصلاح دستوري شامل.",
            formalExample = "The implementation of fiscal policies helped bring about economic stabilization.",
            formalExampleTranslation = "ساعد تطبيق السياسات المالية في إحداث الاستقرار الاقتصادي المنشود.",
            informalMeaning = "التسبب في شجار عائلي بسبب تعليق غير لائق.",
            informalExample = "His careless remark brought about a huge argument at the dinner table.",
            informalExampleTranslation = "تسببت ملاحظته غير المبالية في إشعال شجار كبير على طاولة العشاء."
        ),
        PhrasalVerb(
            id = 32,
            verb = "Calm down",
            summaryMeaning = "يهدأ / يُسكّن الروع والتوتر",
            formalMeaning = "استعادة الهدوء المؤسسي واستقرار الأسواق المالية بعد تقلبات حادة.",
            formalExample = "Central bank interventions served to calm down volatile currency markets.",
            formalExampleTranslation = "ساهمت تدخلات البنك المركزي في تهدئة أسواق العملات المتقلبة.",
            informalMeaning = "الطلب من صديق أن يهدأ بعد نوبة غضب.",
            informalExample = "Dude, calm down! Take a deep breath and let's talk peacefully.",
            informalExampleTranslation = "يا صاح، اهدأ! خذ نفساً عميقاً ولنتحدث بهدوء ودون انفعال."
        ),
        PhrasalVerb(
            id = 33,
            verb = "Catch up",
            summaryMeaning = "يلحق بالآخرين / يتبادل المستجدات والأخبار",
            formalMeaning = "تقليص الفجوة التكنولوجية أو الإنتاجية مع المنافسين الدوليين.",
            formalExample = "Domestic producers are striving to catch up with foreign technological benchmarks.",
            formalExampleTranslation = "يسعى المنتجون المحليون جاهدين للحاق بالمعايير التكنولوجية الأجنبية.",
            informalMeaning = "الجلوس مع صديق قديم لاحتساء القهوة ومعرفة أخباره الأخيرة.",
            informalExample = "Let's grab a coffee this weekend and catch up on everything!",
            informalExampleTranslation = "دعنا نتناول القهوة في نهاية هذا الأسبوع لنتجاذب أطراف الحديث ونعرف آخر الأخبار!"
        ),
        PhrasalVerb(
            id = 34,
            verb = "Check out",
            summaryMeaning = "يسجل المغادرة من فندق / يتحقق من أمر / يستكشف",
            formalMeaning = "إتمام إجراءات المغادرة الرسمية وتسوية الفواتير في الفندق أو المشفى.",
            formalExample = "Guests are required to check out at the reception desk before noon.",
            formalExampleTranslation = "يُطلب من النزلاء إتمام إجراءات المغادرة لدى مكتب الاستقبال قبل الظهيرة.",
            informalMeaning = "إلقاء نظرة على سيارة جميلة أو فحص شيء رائع.",
            informalExample = "Hey, check out that sleek sports car parked across the street!",
            informalExampleTranslation = "مهلاً، ألقِ نظرة على تلك السيارة الرياضية الأنيقة الواقفة في المقابل!"
        ),
        PhrasalVerb(
            id = 35,
            verb = "Cheer up",
            summaryMeaning = "يبتهج ويرفع معنويات شخص",
            formalMeaning = "تحفيز ورفع الروح المعنوية لمنسوبي المؤسسة خلال فترات الأزمات.",
            formalExample = "The CEO delivered an inspiring address to cheer up anxious project personnel.",
            formalExampleTranslation = "ألقى الرئيس التنفيذي خطاباً ملهماً لرفع معنويات موظفي المشروع القلقين.",
            informalMeaning = "محاولة إضحاك صديق حزين بشراء هدية أو آيس كريم.",
            informalExample = "Cheer up! I brought your favorite chocolate cake to make you smile.",
            informalExampleTranslation = "ابتسم ولا تحزن! أحضرت لك كعكة الشوكولاتة المفضلة لتسعدك."
        ),
        PhrasalVerb(
            id = 36,
            verb = "Clean up",
            summaryMeaning = "ينظف مكاناً / يحقق أرباحاً طائلة / يقضي على الفساد",
            formalMeaning = "تطهير بيئي لمواقع ملوثة، أو استئصال الفساد الإداري.",
            formalExample = "The municipal authority initiated a multi-phase program to clean up contaminated waterways.",
            formalExampleTranslation = "أطلقت البلدية برنامجاً متعدد المراحل للتطهير البيئي للمجاري المائية الملوثة.",
            informalMeaning = "تحقيق مكاسب مالية ضخمة وبسرعة قياسية في صفقة.",
            informalExample = "They really cleaned up in the stock market with that tech investment.",
            informalExampleTranslation = "لقد حصدوا أرباحاً خيالية في سوق الأسهم من ذلك الاستثمار التقني."
        ),
        PhrasalVerb(
            id = 37,
            verb = "Come up with",
            summaryMeaning = "يبتكر فكرة / يوفّر مبلغاً من المال",
            formalMeaning = "ابتكار منهجية بحثية علمية أو حل استراتيجي لتحدٍ تقني.",
            formalExample = "The R&D team managed to come up with a patented energy-efficient sensor.",
            formalExampleTranslation = "نجح فريق البحث والتطوير في ابتكار وتطوير مستشعر حاصل على براءة اختراع وموفر للطاقة.",
            informalMeaning = "تدبير مبلغ الإيجار قبل نهاية الشهر.",
            informalExample = "I need to come up with five hundred bucks before rent is due on Friday.",
            informalExampleTranslation = "يجب أن أدبر 500 دولار قبل موعد استحقاق الإيجار يوم الجمعة."
        ),
        PhrasalVerb(
            id = 38,
            verb = "Cut down on",
            summaryMeaning = "يقلل ويخفض الاستهلاك أو النفقات",
            formalMeaning = "الخفض المنهجي للانبعاثات الكربونية أو المصاريف التشغيلية.",
            formalExample = "The conglomerate pledged to cut down on carbon emissions by forty percent by 2030.",
            formalExampleTranslation = "تعهدت المجموعة التجارية بخفض الانبعاثات الكربونية بنسبة 40% بحلول عام 2030.",
            informalMeaning = "التقليل من شرب القهوة أو السكريات لأسباب صحية.",
            informalExample = "My doctor told me to cut down on sugary sodas and junk food.",
            informalExampleTranslation = "نصحني طبيبي بالتقليل من المشروبات الغازية السكرية والوجبات السريعة."
        ),
        PhrasalVerb(
            id = 39,
            verb = "Deal with",
            summaryMeaning = "يتعامل مع / يعالج مشكلة أو موضوعاً",
            formalMeaning = "إدارة الأزمات، أو الفصل القضائي في نزاع تجاري دولي.",
            formalExample = "Specialized legal arbiters will deal with the maritime territorial dispute.",
            formalExampleTranslation = "سيتولى محكمون قانونيون متخصصون التعامل والفصل في النزاع الحدودي البحري.",
            informalMeaning = "تحمل شخص مزعج أو تصريف أمور البيت اليومية.",
            informalExample = "I honestly can't deal with his constant complaining today.",
            informalExampleTranslation = "بصراحة لا أستطيع أن أتحمل أو أتعامل مع تذمره المستمر اليوم."
        ),
        PhrasalVerb(
            id = 40,
            verb = "Drop by",
            summaryMeaning = "يمر ويزور في زيارة خاطفة وسريعة",
            formalMeaning = "زيارة بروتوكولية قصيرة وغير رسمية لموقع أو منشأة.",
            formalExample = "The minister may drop by the exhibition pavilion to greet industry delegates.",
            formalExampleTranslation = "قد يمر الوزير في زيارة تفقدية سريعة لجناح المعرض لتحية الوفود المشاركة.",
            informalMeaning = "المرور على منزل صديق دون موعد مسبق لإلقاء التحية.",
            informalExample = "Feel free to drop by my place whenever you're in the neighborhood!",
            informalExampleTranslation = "لا تتردد في المرور على منزلي متى ما كنت قريباً من الحي!"
        ),
        PhrasalVerb(
            id = 41,
            verb = "End up",
            summaryMeaning = "ينتهي به المطاف والمصير إلى وضع ما",
            formalMeaning = "الوصول النهائي إلى نتيجة إحصائية أو إفلاس مؤسسي.",
            formalExample = "Unchecked inflation could cause multiple lending institutions to end up insolvent.",
            formalExampleTranslation = "قد يؤدي التضخم غير المنضبط إلى أن ينتهي المطاف بعدة مؤسسات إقراض إلى الإفلاس.",
            informalMeaning = "الضياع في الطريق والوصول إلى مكان غير متوقع.",
            informalExample = "We took a wrong turn and ended up in a tiny remote village in the mountains.",
            informalExampleTranslation = "سلكنا منعطفاً خاطئاً وانتهى بنا المطاف في قرية جبلية صغيرة ونائية."
        ),
        PhrasalVerb(
            id = 42,
            verb = "Fall apart",
            summaryMeaning = "ينهار ويتفكك إلى أجزاء / يفقد السيطرة على مشاعره",
            formalMeaning = "انهيار تحالف سياسي، اتفاقية سلام أو هيكل اقتصادي.",
            formalExample = "Analysts predicted the coalition would fall apart after legislative disagreements.",
            formalExampleTranslation = "توقع المحللون أن ينهار التحالف ويتفكك في أعقاب الخلافات التشريعية.",
            informalMeaning = "تلف غرض قديم وتفككه باليد، أو الانهيار من الحزن الشديد.",
            informalExample = "These cheap sneakers are already falling apart after just two weeks of use.",
            informalExampleTranslation = "هذا الحذاء الرخيص بدأ يتفكك ويهترئ بالفعل بعد أسبوعين فقط من ارتدائه."
        ),
        PhrasalVerb(
            id = 43,
            verb = "Fill out",
            summaryMeaning = "يملأ استمارة / يكتسب وزناً أو قواماً",
            formalMeaning = "استكمال البيانات الرسمية في نموذج طلب حكومي أو تأشيرة.",
            formalExample = "Applicants must fill out the consular visa petition accurately and legibly.",
            formalExampleTranslation = "يجب على المتقدمين ملء استمارة طلب التأشيرة القنصلية بدقة وبخط واضح.",
            informalMeaning = "زيادة وزن شخص نحيف وبناء عضلات مع التقدم في العمر.",
            informalExample = "He was really skinny as a teen, but he filled out after hitting the gym.",
            informalExampleTranslation = "كان نحيفاً جداً في مراهقته، لكن بنيته امتلأت وقويت بعد ممارسة الرياضة."
        ),
        PhrasalVerb(
            id = 44,
            verb = "Get away",
            summaryMeaning = "يهرب وينجو / يذهب في إجازة للاستجمام",
            formalMeaning = "الهروب من الاحتجاز القانوني، أو تجنب المساءلة القضائية.",
            formalExample = "The suspects managed to get away before maritime security could intercept them.",
            formalExampleTranslation = "تمكن المشتبه بهم من الفرار قبل أن تتمكن قوات الأمن البحري من اعتراضهم.",
            informalMeaning = "الهروب من روتين العمل لأخذ إجازة قصيرة والاسترخاء.",
            informalExample = "I've been working so hard; I really need to get away for a few days to the beach.",
            informalExampleTranslation = "كنت أعمل بجد مفرط؛ أحتاج حقاً للهروب لبضعة أيام والاستجمام على الشاطئ."
        ),
        PhrasalVerb(
            id = 45,
            verb = "Get over",
            summaryMeaning = "يتعافى من مرض / يتجاوز صدمة أو تجربة عاطفية",
            formalMeaning = "تخطي وتجاوز أزمة ائتمانية أو عجز مالي عبر سياسات إنقاذ.",
            formalExample = "The banking sector will take several fiscal quarters to get over the liquidity crisis.",
            formalExampleTranslation = "سيستغرق القطاع المصرفي عدة أرباع مالية ليتجاوز أزمة السيولة ويتعافى منها.",
            informalMeaning = "تجاوز انفصال عاطفي أو الدهشة الشديدة من خبر.",
            informalExample = "It took him six months to get over his ex-girlfriend.",
            informalExampleTranslation = "استغرق الأمر منه ستة أشهر ليتجاوز أثر فراق حبيبته السابقة."
        ),
        PhrasalVerb(
            id = 46,
            verb = "Get rid of",
            summaryMeaning = "يتخلص من غرض أو عادة أو مشكلة",
            formalMeaning = "التخلص الآمن والصحي من النفايات الخطرة وفق الاشتراطات البيئية.",
            formalExample = "Industrial chemical plants must safely get rid of toxic waste according to federal law.",
            formalExampleTranslation = "يجب على مصانع الكيماويات التخلص من النفايات السامة بأمان وفقاً للقانون الفيدرالي.",
            informalMeaning = "رمي كراكيب البيت القديمة أو التملص من شخص متطفل.",
            informalExample = "I need to get rid of all these old magazines cluttering my room.",
            informalExampleTranslation = "أحتاج إلى التخلص من كل هذه المجلات القديمة التي تملأ غرفتي فوضى."
        ),
        PhrasalVerb(
            id = 47,
            verb = "Give back",
            summaryMeaning = "يُرجع شيئاً لصاحبه / يرد الجميل للمجتمع",
            formalMeaning = "إعادة الأراضي، الممتلكات المصادرة أو الأصول المنهوبة لأصحابها الشرعيين.",
            formalExample = "The tribunal ordered the corporation to give back expropriated assets to local owners.",
            formalExampleTranslation = "أمرت المحكمة الشركة بإعادة الأصول والممتلكات المصادرة إلى ملاكها الأصليين.",
            informalMeaning = "إرجاع غرض مستعار لصديق أو العمل التطوعي في الحي.",
            informalExample = "Make sure you give back the laptop you borrowed from Sara tomorrow.",
            informalExampleTranslation = "احرص على إعادة الحاسوب المحمول الذي استعرته من سارة غداً."
        ),
        PhrasalVerb(
            id = 48,
            verb = "Give in",
            summaryMeaning = "يرضخ ويستسلم لمطلب / يسلّم واجباً مدرسياً",
            formalMeaning = "الرضوخ للمطالب الدبلوماسية أو شروط التفاوض بعد ضغوط اقتصادية.",
            formalExample = "The opposing delegation refused to give in regarding sovereign maritime claims.",
            formalExampleTranslation = "رفض وفد المعارضة الرضوخ فيما يخص المطالبات الإقليمية بالسيادة البحرية.",
            informalMeaning = "التنازل أمام إلحاح الأطفال وشراء الحلوى لهم.",
            informalExample = "The toddler cried for candy in the store, and the dad finally gave in.",
            informalExampleTranslation = "بكى الطفل الصغير طالباً الحلوى في المتجر، واستسلم الأب لطلبه في النهاية."
        ),
        PhrasalVerb(
            id = 49,
            verb = "Go ahead",
            summaryMeaning = "يمضي قدماً / يبدأ بعد الحصول على الإذن",
            formalMeaning = "الموافقة الرسمية والتصريح ببدء تنفيذ مشروع استثماري ضخم.",
            formalExample = "The regulatory authority granted approval for the pipeline project to go ahead.",
            formalExampleTranslation = "منحت الهيئة التنظيمية الموافقة الرسمية للمضي قدماً في مشروع خط الأنابيب.",
            informalMeaning = "إعطاء الإذن لشخص بأخذ قطعة بيتزا أو البدء في الكلام.",
            informalExample = "Can I have the last slice of pizza? Sure, go ahead!",
            informalExampleTranslation = "هل يمكنني تناول آخر قطعة بيتزا؟ بالطبع، تفضل ومرحى بك!"
        ),
        PhrasalVerb(
            id = 50,
            verb = "Go on",
            summaryMeaning = "يستمر ويواصل / يحدث ويجري",
            formalMeaning = "استمرار سريان المعاهدة أو استكمال المفاوضات بدون انقطاع.",
            formalExample = "Treaty deliberations will go on until consensus on emissions targets is reached.",
            formalExampleTranslation = "ستستمر مداولات المعاهدة حتى يتم التوصل إلى إجماع بشأن أهداف الانبعاثات.",
            informalMeaning = "السؤال عما يدور من أحداث ('What's going on?') أو حث شخص على إكمال حديثه.",
            informalExample = "What is going on here? Why are you guys yelling?",
            informalExampleTranslation = "ما الذي يجري ويحدث هنا؟ لماذا تصرخون هكذا؟"
        ),
        PhrasalVerb(
            id = 51,
            verb = "Grow up",
            summaryMeaning = "يكبر وينضج / ينشأ في بيئة معينة",
            formalMeaning = "التطور التدريجي للأسواق الناشئة أو النضج المؤسسي لمنظمة.",
            formalExample = "The domestic tech sector has grown up into an indispensable economic pillar.",
            formalExampleTranslation = "نضج وتطور قطاع التكنولوجيا المحلي ليصبح ركيزة اقتصادية لا غنى عنها.",
            informalMeaning = "مطالبة شخص بالتصرف بنضج والتوقف عن الحركات الطفولية.",
            informalExample = "Stop acting like a spoiled child and grow up!",
            informalExampleTranslation = "توقف عن التصرف كطفل مدلل وانضج قليلاً!"
        ),
        PhrasalVerb(
            id = 52,
            verb = "Hang out",
            summaryMeaning = "يقضي وقتاً للاستجمام مع الأصدقاء / ينشر الغسيل",
            formalMeaning = "تعليق ونشر إشارات تحذيرية أو إعلانات عامة في الأماكن المشتركة.",
            formalExample = "Facility safety guidelines mandate that warning banners be hung out visibly.",
            formalExampleTranslation = "تفرض إرشادات السلامة في المنشأة تعليق لافتات التحذير بشكل بارز للعيان.",
            informalMeaning = "التسكع وقضاء وقت ممتع ومريح مع الأصدقاء.",
            informalExample = "Do you want to hang out at the mall this Saturday evening?",
            informalExampleTranslation = "هل تود أن نتسكع ونقضي بعض الوقت في المركز التجاري مساء السبت؟"
        ),
        PhrasalVerb(
            id = 53,
            verb = "Hit on",
            summaryMeaning = "يهتدي لفكرة فجأة / يغازل شخصاً بجرأة",
            formalMeaning = "الاهتداء غير المتوقع إلى كشف علمي أو حل تقني مبدع.",
            formalExample = "Biochemical researchers hit on a promising compound during randomized screening tests.",
            formalExampleTranslation = "اهتدى باحثو الكيمياء الحيوية إلى مركب واعد خلال اختبارات الفرز العشوائي.",
            informalMeaning = "مغازلة شخص في مقهى أو حفلة لجذب اهتمامه العاطفي.",
            informalExample = "He tried to hit on the barista by complimenting her smile.",
            informalExampleTranslation = "حاول مغازلة معدّة القهوة بإبداء إعجابه بابتسامتها."
        ),
        PhrasalVerb(
            id = 54,
            verb = "Hold up",
            summaryMeaning = "يؤخر ويعطل / يسطو مسلحاً / يصمد ويبقى متماسكاً",
            formalMeaning = "تأخير غير مقصود للإجراءات التشريعية أو مسار القضية القانونية.",
            formalExample = "A jurisdictional conflict held up the extradition proceedings for several months.",
            formalExampleTranslation = "أدى تنازع الاختصاص القضائي إلى تعطيل إجراءات تسليم المطلوبين لعدة أشهر.",
            informalMeaning = "التعرض لعملية سطو مسلح، أو التمسك بالقوة في أزمة.",
            informalExample = "Sorry I'm late; traffic was held up by a major accident on the bridge.",
            informalExampleTranslation = "آسف لتأخري؛ تعطلت حركة المرور بسبب حادث كبير على الجسر."
        ),
        PhrasalVerb(
            id = 55,
            verb = "Keep on",
            summaryMeaning = "يستمر بلا توقف / يبقي على موظف في عمله",
            formalMeaning = "الاحتفاظ بالعاملين المؤهلين وتجديد عقودهم المؤسسية.",
            formalExample = "The director decided to keep on core administrative staff throughout restructuring.",
            formalExampleTranslation = "قرر المدير الاحتفاظ بموظفي الإدارة الأساسيين وتثبيتهم طوال مرحلة إعادة الهيكلة.",
            informalMeaning = "الإصرار على فعل شيء رغم التحذيرات المتكررة.",
            informalExample = "Why does he keep on texting me even after I said I was busy?",
            informalExampleTranslation = "لماذا يواصل مراسلتي باستمرار حتى بعد أن أخبرته أنني مشغول؟"
        ),
        PhrasalVerb(
            id = 56,
            verb = "Kick off",
            summaryMeaning = "يبدأ ويدشن فعالية / ينطلق / يثير شجاراً",
            formalMeaning = "التدشين الافتتاحي لمؤتمر اقتصادي دولي أو حملة وطنية.",
            formalExample = "The prime minister will kick off the environmental summit with a keynote address.",
            formalExampleTranslation = "سيدشن رئيس الوزراء القمة البيئية رسمياً بخطاب افتتاحي رئيسي.",
            informalMeaning = "بدء مباراة كرة القدم، أو اندلاع شجار مفاجئ في الشارع.",
            informalExample = "The soccer match kicks off at 8 PM tonight, so grab some snacks!",
            informalExampleTranslation = "تنطلق مباراة كرة القدم في الثامنة مساء اليوم، فاحرص على تجهيز التسالي!"
        ),
        PhrasalVerb(
            id = 57,
            verb = "Let down",
            summaryMeaning = "يخيّب أمل شخص / ينزل غرضاً لأسفل",
            formalMeaning = "الإخلال بالالتزام التعاقدي أو الفشل في تلبية توقعات أصحاب المصلحة.",
            formalExample = "The supplier's delivery delays let down key retail stakeholders at launch.",
            formalExampleTranslation = "خيّب تأخر شحنات المورّد آمال كبار أصحاب المصلحة والشركاء عند إطلاق المنتج.",
            informalMeaning = "إحباط صديق أو التراجع عن وعد قدمته له.",
            informalExample = "I promised I'd attend his recital; I can't let him down.",
            informalExampleTranslation = "وعدته بحضور حفل عزفه؛ ولا يمكنني أن أخيّب أمله وأخذله أبداً."
        ),
        PhrasalVerb(
            id = 58,
            verb = "Look into",
            summaryMeaning = "يحقق في أمر ويفحصه بعناية",
            formalMeaning = "إجراء تحقيق رسمي من قِبل جهة رقابية في مخالفات مالية أو إدارية.",
            formalExample = "Internal affairs will rigorously look into allegations of departmental misconduct.",
            formalExampleTranslation = "ستتولى الشؤون الداخلية التحقيق والتدقيق بصرامة في مزاعم سوء السلوك بالقسم.",
            informalMeaning = "التحقق من معلومة أو فحص مشكلة صغيرة في المنزل.",
            informalExample = "My Wi-Fi is acting weird; let me look into the router settings.",
            informalExampleTranslation = "شبكة الواي فاي تتصرف بغرابة؛ دعني أفحص وأتحقق من إعدادات جهاز التوجيه."
        ),
        PhrasalVerb(
            id = 59,
            verb = "Look out",
            summaryMeaning = "يحذر وينتبه من خطر داهم",
            formalMeaning = "رصد المخاطر التشغيلية والترقب الوقائي للأزمات السوقية.",
            formalExample = "Risk officers must look out for liquidity volatility in international portfolio markets.",
            formalExampleTranslation = "يجب على مسؤولي المخاطر ترقب وحذر تقلبات السيولة في أسواق المحافظ الدولية.",
            informalMeaning = "صيحة تحذيرية عاجلة لتفادي خطر وشيك كسيارة مسرعة.",
            informalExample = "Look out! That cyclist is speeding right behind you!",
            informalExampleTranslation = "انتبه واحذر! ذلك الراكب على الدراجة مسرع خلفك تماماً!"
        ),
        PhrasalVerb(
            id = 60,
            verb = "Make sense of",
            summaryMeaning = "يفهم ويستوعب أمراً مبهماً ومعقداً",
            formalMeaning = "تفسير وتحليل مجموعة بيانات معقدة أو نصوص تشريعية مبهمة.",
            formalExample = "The advisory panel tried to make sense of conflicting macroeconomic indicators.",
            formalExampleTranslation = "حاول الفريق الاستشاري استيعاب وفهم المؤشرات الاقتصادية الكلية المتضاربة.",
            informalMeaning = "فهم خط كتابة رديء أو تعليمات جهاز غير واضحة.",
            informalExample = "Can you make sense of this doctor's messy handwriting on the prescription?",
            informalExampleTranslation = "هل تستطيع قراءة وفهم خط الطبيب الرديء على هذه الوصفة الطبية؟"
        ),
        PhrasalVerb(
            id = 61,
            verb = "Move on",
            summaryMeaning = "يمضي قدماً ويتجاوز الماضي / ينتقل لنقطة تالية",
            formalMeaning = "الانتقال للبند التالي في جدول أعمال الجمعية العمومية.",
            formalExample = "With clause four ratified, the assembly may move on to proposed statutory amendments.",
            formalExampleTranslation = "بعد إقرار البند الرابع، يمكن للجمعية الانتقال إلى التعديلات القانونية المقترحة.",
            informalMeaning = "نسيان تجربة سابقة حزينة وفتح صفحة جديدة في الحياة.",
            informalExample = "You can't dwell on past mistakes forever; you've got to move on.",
            informalExampleTranslation = "لا يمكنك التحسر على أخطاء الماضي إلى الأبد؛ يجب أن تتجاوز الأمر وتمضي قدماً."
        ),
        PhrasalVerb(
            id = 62,
            verb = "Pass away",
            summaryMeaning = "يتوفى ويفارق الحياة (تعبير مهذب)",
            formalMeaning = "الصياغة الرسمية والمهذبة لإعلان وفاة شخصية بارزة أو مسؤول.",
            formalExample = "The ambassador passed away peacefully after an exemplary diplomatic tenure.",
            formalExampleTranslation = "وافت المنية السفير في سلام بعد مسيرة دبلوماسية يحتذى بها.",
            informalMeaning = "مواساة صديق في وفاة قريبه أو حيوانه الأليف.",
            informalExample = "Her beloved grandmother sadly passed away over the winter break.",
            informalExampleTranslation = "للأسف توفيت جدتها الحبيبة بسلام خلال عطلة الشتاء."
        ),
        PhrasalVerb(
            id = 63,
            verb = "Pay back",
            summaryMeaning = "يسدد ديناً مالياً / ينتقم ويرد الصاع صاعين",
            formalMeaning = "الوفاء بالالتزامات الائتمانية وسداد أصل القرض والفوائد المستحقة.",
            formalExample = "The sovereign borrower is required to pay back the infrastructure loan within ten years.",
            formalExampleTranslation = "يتعين على المقترض السيادي سداد قرض البنية التحتية بالكامل خلال عشر سنوات.",
            informalMeaning = "إرجاع ثمن وجبة دفعها صديق، أو الانتقام من مقلب.",
            informalExample = "Thanks for paying for lunch; I will pay you back as soon as I get cash.",
            informalExampleTranslation = "شكراً لدفعك ثمن الغداء؛ سأسدد لك المبلغ فور حصولي على نقود."
        ),
        PhrasalVerb(
            id = 64,
            verb = "Pick up",
            summaryMeaning = "يلتقط شيئاً / يقل شخصاً بالسيارة / يتعلم بسرعة",
            formalMeaning = "تحسن وانتعاش المؤشرات الاقتصادية العامة والطلب في الأسواق.",
            formalExample = "Retail analysts project sales volumes will pick up during the upcoming holiday quarter.",
            formalExampleTranslation = "يتوقع محللو التجزئة أن تنتعش وتتحسن أحجام المبيعات خلال ربع العطلات القادم.",
            informalMeaning = "أخذ صديق بالسيارة في الطريق، أو الرد على رنين الهاتف.",
            informalExample = "Can you pick me up from the airport around six o'clock?",
            informalExampleTranslation = "هل يمكنك أن تقلني بسيارتك من المطار في حوالي الساعة السادسة؟"
        ),
        PhrasalVerb(
            id = 65,
            verb = "Point out",
            summaryMeaning = "يشير إلى / يلفت الانتباه لملحوظة",
            formalMeaning = "توضيح ثغرة قانونية أو لفت الانتباه لخلل إجرائي في مراجعة العقود.",
            formalExample = "Legal counsel took care to point out discrepancies in the proposed contractual warranty.",
            formalExampleTranslation = "حرص المستشار القانوني على الإشارة إلى التناقضات في الضمان التعاقدي المقترح.",
            informalMeaning = "لفت انتباه شخص لشيء غريب في ملابسه أو على الطريق.",
            informalExample = "She pointed out that I had put on my sweater inside out this morning.",
            informalExampleTranslation = "لفتت انتباهي إلى أنني كنت أرتدي كنزتي بالمقلوب هذا الصباح."
        ),
        PhrasalVerb(
            id = 66,
            verb = "Pull over",
            summaryMeaning = "يركن السيارة على جانب الطريق",
            formalMeaning = "أمر أمني رسمي يوجهه ضابط الدورية لسائق مركبة للتوقف الجانبي.",
            formalExample = "Highway patrol officers instructed the transport driver to pull over for inspection.",
            formalExampleTranslation = "أمر ضباط دورية الطرق السريعة سائق النقل بركن الشاحنة جانباً للتفتيش.",
            informalMeaning = "التوقف بالسيارة جانباً للرد على مكالمة مهمة أو تفقد الخريطة.",
            informalExample = "Pull over near the gas station so I can buy a bottle of water.",
            informalExampleTranslation = "اركن السيارة جانباً قرب محطة الوقود حتى أشتري زجاجة ماء."
        ),
        PhrasalVerb(
            id = 67,
            verb = "Put out",
            summaryMeaning = "يطفئ النار أو السجائر / يصدر بياناً / ينزعج ويتكلف",
            formalMeaning = "إصدار بلاغ رسمي أو بيان صحفي لوسائل الإعلام.",
            formalExample = "The press office will put out a formal statement regarding the maritime incident.",
            formalExampleTranslation = "سيصدر المكتب الصحفي بياناً رسمياً للرأي العام بشأن الحادث البحري.",
            informalMeaning = "إخماد حريق صغير في المطبخ، أو الشعور بالانزعاج لتقديم معروف ثقيل.",
            informalExample = "Firefighters acted heroically to put out the warehouse blaze.",
            informalExampleTranslation = "تصرف رجال الإطفاء ببطولة لإخماد حريق المستودع بالكامل."
        ),
        PhrasalVerb(
            id = 68,
            verb = "Put up with",
            summaryMeaning = "يتحمل ويصبر على وضع أو شخص مزعج",
            formalMeaning = "التسامح المؤسسي المؤقت مع ظروف تشغيلية غير مثالية تحت الضرورة.",
            formalExample = "The committee will not put up with recurring non-compliance in procurement tenders.",
            formalExampleTranslation = "لن تتهاون اللجنة ولن تتحمل عدم الامتثال المتكرر في مناقصات المشتريات.",
            informalMeaning = "الصبر على تصرفات جار مزعج يصدر ضجيجاً متواصلاً.",
            informalExample = "I don't know how she puts up with her noisy upstairs neighbors every night.",
            informalExampleTranslation = "لا أعرف كيف تصبر وتتحمل جيرانها المزعجين في الطابق العلوي كل ليلة."
        ),
        PhrasalVerb(
            id = 69,
            verb = "Rule out",
            summaryMeaning = "يستبعد خياراً أو فرضية تماماً",
            formalMeaning = "الاستبعاد الرسمي لاحتمال أو فرضية طبية/جنائية بناءً على براهين قاطعة.",
            formalExample = "Forensic investigators officially ruled out foul play in the industrial explosion.",
            formalExampleTranslation = "استبعد المحققون الجنائيون رسمياً وجود شبهة جنائية في الانفجار الصناعي.",
            informalMeaning = "استبعاد الذهاب إلى مكان بسبب غلاء أسعاره أو بعد مسافته.",
            informalExample = "We can rule out that fancy restaurant; their prices are way too high for us.",
            informalExampleTranslation = "يمكننا استبعاد ذلك المطعم الفاخر؛ فأسعاره مرتفعة جداً عن ميزانيتنا."
        ),
        PhrasalVerb(
            id = 70,
            verb = "Run away",
            summaryMeaning = "يهرب ويفر / يتهرب من المسؤولية",
            formalMeaning = "الفرار غير الشرعي لتجنب المحاكمة القضائية أو تسليم المطلوبين.",
            formalExample = "Authorities issued a notice for individuals attempting to run away from detention.",
            formalExampleTranslation = "أصدرت السلطات تعميماً أمنياً بشأن الأفراد الذين يحاولون الفرار من الاحتجاز.",
            informalMeaning = "هروب كلب أليف من بوابة الحديقة، أو الخوف من مواجهة المشاكل.",
            informalExample = "Don't run away from your problems; face them and fix them!",
            informalExampleTranslation = "لا تهرب من مشاكلك؛ بل واجهها وحلها بشجاعة!"
        ),
        PhrasalVerb(
            id = 71,
            verb = "Set off",
            summaryMeaning = "ينطلق في رحلة / يُفعّل جرس إنذار / يُحدث رد فعل",
            formalMeaning = "بدء تنفيذ مرحلة تشغيلية، أو تفعيل بروتوكول طوارئ وقائي.",
            formalExample = "The security breach set off automated lockdown sequences across the research campus.",
            formalExampleTranslation = "أدى الاختراق الأمني إلى تفعيل تسلسل الإغلاق التلقائي في مجمع الأبحاث.",
            informalMeaning = "الانطلاق في رحلة برية فجراً، أو إطلاق ألعاب نارية احتفالية.",
            informalExample = "We need to set off early at dawn to beat the highway traffic.",
            informalExampleTranslation = "علينا الانطلاق مبكراً عند الفجر لتفادي الزحام على الطريق السريع."
        ),
        PhrasalVerb(
            id = 72,
            verb = "Show off",
            summaryMeaning = "يتباهى ويتفاخر بما يملك",
            formalMeaning = "استعراض الإنجازات المؤسسية والابتكارات في المعارض الدولية الرسمية.",
            formalExample = "The tech pavilion offered domestic startups a venue to show off aerospace patents.",
            formalExampleTranslation = "أتاح جناح التكنولوجيا للشركات الناشئة منصة لاستعراض براءات اختراع الفضاء.",
            informalMeaning = "التباهي والتفاخر بساعة جديدة أو مهارة أمام الأصدقاء بغرور.",
            informalExample = "He loves to show off his expensive designer clothes whenever he visits.",
            informalExampleTranslation = "يحب دائماً التباهي والتفاخر بملابسه باهظة الثمن كلما زارنا."
        ),
        PhrasalVerb(
            id = 73,
            verb = "Show up",
            summaryMeaning = "يحضر ويصل في الموعد / يظهر للعيان",
            formalMeaning = "المثول أمام المحكمة أو الحضور الإلزامي لاجتماع الجمعية العمومية.",
            formalExample = "The subpoenaed witness failed to show up for the parliamentary inquiry deposition.",
            formalExampleTranslation = "تخلف الشاهد المستدعى عن الحضور والمثول أمام جلسة التحقيق البرلماني.",
            informalMeaning = "الظهور المفاجئ في حفلة أو التأخر عن موعد العشاء.",
            informalExample = "I was surprised when my childhood friend showed up at my birthday party.",
            informalExampleTranslation = "تفاجأت وسعدت عندما حضر وظهر صديق طفولتي في حفل عيد ميلادي."
        ),
        PhrasalVerb(
            id = 74,
            verb = "Shut down",
            summaryMeaning = "يغلق منشأة / يوقف تشغيل نظام أو جهاز",
            formalMeaning = "الإغلاق التنظيمي أو المصرفي لمنشأة غير ملتزمة بمعايير السلامة.",
            formalExample = "Environmental regulators voted to shut down the coal plant due to sulfur emissions.",
            formalExampleTranslation = "صوتت الهيئات البيئية لإغلاق محطة الفحم رسمياً بسبب انبعاثات الكبريت الضارة.",
            informalMeaning = "إيقاف تشغيل جهاز الكمبيوتر قبل الذهاب للنوم.",
            informalExample = "Remember to save your work before you shut down your PC for the night.",
            informalExampleTranslation = "تذكر حفظ عملك وملفاتك قبل إيقاف تشغيل حاسوبك ليلاً."
        ),
        PhrasalVerb(
            id = 75,
            verb = "Slow down",
            summaryMeaning = "يُبطئ السرعة / يهدئ وتيرة العمل والإجهاد",
            formalMeaning = "التباطؤ الإحصائي لمؤشرات النمو الاقتصادي في فترات الانكماش.",
            formalExample = "Central bank reports indicate consumer spending will slow down in the fourth quarter.",
            formalExampleTranslation = "تشير تقارير البنك المركزي إلى أن وتيرة الإنفاق الاستهلاكي ستتباطأ في الربع الأخير.",
            informalMeaning = "تخفيف السرعة بالسيارة عند مناطق المدارس أو أخذ استراحة من التعب.",
            informalExample = "Slow down! There are speed bumps and kids playing on this street.",
            informalExampleTranslation = "أبطئ سرعتك! توجد مطبات وأطفال يلعبون في هذا الشارع."
        ),
        PhrasalVerb(
            id = 76,
            verb = "Sort out",
            summaryMeaning = "يرتّب ويحل مشكلة / يصنف وينظم أغراضاً",
            formalMeaning = "تسوية وتوفيق الخلافات الإدارية وتصنيف البيانات في تدقيق الحسابات.",
            formalExample = "Senior diplomats met in Geneva to sort out border taxation disagreements.",
            formalExampleTranslation = "التقى كبار الدبلوماسيين في جنيف لتسوية وحل الخلافات المتعلقة بالضرائب الحدودية.",
            informalMeaning = "تنظيم خزانة الملابس أو حل خلاف ودي بين رفقاء السكن.",
            informalExample = "Give me twenty minutes to sort out my messy desk and we can go.",
            informalExampleTranslation = "أمهلني عشرين دقيقة لأرتب مكتبي المبعثر ثم يمكننا الانطلاق معاً."
        ),
        PhrasalVerb(
            id = 77,
            verb = "Speed up",
            summaryMeaning = "يُسرّع الوتيرة ويزيد السرعة",
            formalMeaning = "تسريع وتيرة إجراءات الموافقات التنظيمية لتسهيل الاستثمار الأجنبي.",
            formalExample = "The ministry unveiled new digital workflows to speed up visa issuance protocols.",
            formalExampleTranslation = "كشفت الوزارة عن مسارات رقمية جديدة لتسريع إجراءات وبروتوكولات إصدار التأشيرات.",
            informalMeaning = "القيادة بسرعة أكبر أو الاستعجال لتجنب التأخر على موعد.",
            informalExample = "We need to speed up if we want to catch the last train tonight!",
            informalExampleTranslation = "يجب أن نزيد من سرعتنا ونستعجل إن أردنا اللحاق بآخر قطار الليلة!"
        ),
        PhrasalVerb(
            id = 78,
            verb = "Stick to",
            summaryMeaning = "يلتزم بخطة أو نظام / يلتصق بشيء",
            formalMeaning = "الالتزام الصارم بالمعايير القانونية أو البنود التعاقدية المتفق عليها.",
            formalExample = "Contractors are legally obliged to stick to the approved engineering blueprints.",
            formalExampleTranslation = "يلتزم المقاولون قانونياً بالتقيد الصارم بالمخططات الهندسية المعتمدة.",
            informalMeaning = "الالتزام بحمية غذائية صحية ومقاومة رغبة تناول الحلوى.",
            informalExample = "It is hard to stick to my diet when there are fresh donuts on the counter.",
            informalExampleTranslation = "من الصعب الالتزام بحميتي الغذائية عندما توجد قطع دونات طازجة على الطاولة."
        ),
        PhrasalVerb(
            id = 79,
            verb = "Take after",
            summaryMeaning = "يشبه أحد الوالدين في الشكل أو الطباع",
            formalMeaning = "وراثة الخصائص الوراثية أو السمات السلوكية في الدراسات الجينية.",
            formalExample = "Clinical genetic studies analyze how offspring take after parents in cardiac health markers.",
            formalExampleTranslation = "تحلل الدراسات الجينية السريرية كيف يرث الأبناء صفات الآباء في مؤشرات صحة القلب.",
            informalMeaning = "ملاحظة تشابه الابن مع والده في حب القهوة أو خفة الظل.",
            informalExample = "He really takes after his father when it comes to musical talent.",
            informalExampleTranslation = "إنه يشبه والده تماماً عندما يتعلق الأمر بالموهبة الموسيقية الفذة."
        ),
        PhrasalVerb(
            id = 80,
            verb = "Take in",
            summaryMeaning = "يستوعب معلومات / يخدع شخصاً / يستضيف في المنزل",
            formalMeaning = "استيعاب وتحليل معطيات استخباراتية أو إيواء لاجئين رسمياً.",
            formalExample = "The humanitarian sanctuary agreed to take in displaced families under UN auspices.",
            formalExampleTranslation = "وافقت المنشأة الإنسانية على استضافة العائلات النازحة تحت رعاية الأمم المتحدة.",
            informalMeaning = "الانخداع بحيلة بائع ماكر، أو تضييق مقاس فستان واسع.",
            informalExample = "Don't be taken in by his smooth talk; he's trying to scam you.",
            informalExampleTranslation = "لا تنخدع بحديثه المعسول؛ فهو يحاول الاحتيال عليك وخداعك."
        ),
        PhrasalVerb(
            id = 81,
            verb = "Take on",
            summaryMeaning = "يتحمل مسؤولية / يوظف عمالاً / يتحدى منافساً",
            formalMeaning = "التعاقد مع قوى عاملة إضافية، أو قبول مسؤولية التزام قانوني جديد.",
            formalExample = "The logistics conglomerate will take on five hundred seasonal warehouse staff.",
            formalExampleTranslation = "ستقوم مجموعة الخدمات اللوجستية بتوظيف 500 موظف موسمي في المستودعات.",
            informalMeaning = "قبول مهمة شاقة إضافية في العمل رغم ضيق الوقت.",
            informalExample = "I can't take on any more freelance projects right now; my schedule is packed.",
            informalExampleTranslation = "لا أستطيع تولي أي مشاريع عمل حر إضافية الآن؛ فجدولي ممتلئ تماماً."
        ),
        PhrasalVerb(
            id = 82,
            verb = "Take over",
            summaryMeaning = "يستحوذ على شركة / يتولى القيادة والسيطرة",
            formalMeaning = "الاستحواذ المؤسسي على حصة مسيطرة في أسهم شركة مساهمة.",
            formalExample = "The multinational telecommunications giant launched a bid to take over its rival.",
            formalExampleTranslation = "أطلق عملاق الاتصالات متعدد الجنسيات عرضاً للاستحواذ المؤسسي على منافسه.",
            informalMeaning = "تولي قيادة السيارة بدلاً من صديق متعب في طريق السفر.",
            informalExample = "You look exhausted; pull over and let me take over the driving for a while.",
            informalExampleTranslation = "تبدو مرهقاً للغاية؛ توقف جانباً ودعني أتولى قيادة السيارة بدلاً منك لبعض الوقت."
        ),
        PhrasalVerb(
            id = 83,
            verb = "Tear down",
            summaryMeaning = "يهدم بناءً / يفكك ويحطم سمعة",
            formalMeaning = "الهدم الإنشائي لمبانٍ آيلة للسقوط بموجب أمر قضائي صادر.",
            formalExample = "The municipal planning commission ordered workers to tear down the condemned structure.",
            formalExampleTranslation = "أمرت لجنة التخطيط بالبلدية العمال بهدم وإزالة المبنى غير المطابق لمعايير السلامة.",
            informalMeaning = "توجيه نقد جارح لإحباط شخص وتدمير ثقته بنفسه.",
            informalExample = "Real friends lift you up; they never try to tear you down.",
            informalExampleTranslation = "الأصدقاء الحقيقيون يرفعون من شأنك؛ ولا يحاولون أبداً تحطيم معنوياتك وإحباطك."
        ),
        PhrasalVerb(
            id = 84,
            verb = "Think over",
            summaryMeaning = "يفكر ويتأمل في قرار بعناية وهدوء",
            formalMeaning = "المداولة الدقيقة من قِبل مجلس الإدارة قبل إبرام صفقة اندماج كبرى.",
            formalExample = "The trustees requested two weeks to think over the proposed merger terms.",
            formalExampleTranslation = "طلب الأمناء مهلة أسبوعين للتفكير والمداولة المتأنية في بنود الاندماج المقترحة.",
            informalMeaning = "التريث قبل الرد على عرض عمل جديد أو شراء سيارة.",
            informalExample = "It is a big decision, so take your time and think it over before giving an answer.",
            informalExampleTranslation = "إنه قرار كبير، لذا خذ وقتك وفكر فيه بروية قبل إعطاء ردك النهائي."
        ),
        PhrasalVerb(
            id = 85,
            verb = "Throw away",
            summaryMeaning = "يرمي في القمامة / يهدر فرصة ثمينة",
            formalMeaning = "إهدار الموارد العامة أو التخلص غير القانوني من مواد خاضعة للرقابة.",
            formalExample = "Public audit findings cautioned agencies against throwing away allocated grant capital.",
            formalExampleTranslation = "حذرت نتائج التدقيق العام الهيئات من إهدار والتفريط في أموال المنح المخصصة.",
            informalMeaning = "رمي بقايا الطعام القديمة أو تضييع فرصة ذهبية بحماقة.",
            informalExample = "Don't throw away your chance to study abroad on a full scholarship!",
            informalExampleTranslation = "لا تهدر وتضيع فرصتك الذهبية للدراسة في الخارج بمنحة كاملة!"
        ),
        PhrasalVerb(
            id = 86,
            verb = "Turn around",
            summaryMeaning = "يحدث تحولاً إيجابياً / يستدير للخلف",
            formalMeaning = "الإنعاش المالي وإعادة هيكلة شركة خاسرة لتحقيق الربحية مجدداً.",
            formalExample = "The newly appointed CEO succeeded in turning around the struggling enterprise within two years.",
            formalExampleTranslation = "نجح الرئيس التنفيذي الجديد في إحداث تحول إيجابي وإنقاذ المؤسسة المتعثرة خلال عامين.",
            informalMeaning = "الاستدارة بالجسد للنظر لمن يناديك من الخلف.",
            informalExample = "Turn around and look! There's a stunning rainbow right behind us!",
            informalExampleTranslation = "استدر وانظر للخلف! يوجد قوس قزح رائع المنظر خلفنا مباشرة!"
        ),
        PhrasalVerb(
            id = 87,
            verb = "Turn into",
            summaryMeaning = "يتحول ويتحول إلى شيء أو حالة جديدة",
            formalMeaning = "التحول الهيكلي لاقتصاد نامٍ إلى مركز تكنولوجي عالمي.",
            formalExample = "Substantial sovereign investment helped turn the coastal city into a major shipping port.",
            formalExampleTranslation = "ساعدت الاستثمارات السيادية الضخمة في تحويل المدينة الساحلية إلى ميناء شحن عالمي كبير.",
            informalMeaning = "تحول نزهة هادئة فجأة إلى فوضى بسبب عاصفة مطرية.",
            informalExample = "Our peaceful picnic turned into total chaos when the thunderstorm hit.",
            informalExampleTranslation = "تحولت نزهتنا الهادئة إلى فوضى عارمة عندما ضربت العاصفة الرعدية فجأة."
        ),
        PhrasalVerb(
            id = 88,
            verb = "Turn off",
            summaryMeaning = "يغلق جهازاً أو صنبوراً / ينفر ويزعج",
            formalMeaning = "إيقاف تشغيل محطات الطاقة أو الصمامات الرئيسية لأغراض الصيانة الوقائية.",
            formalExample = "Maintenance crews will turn off the main water pipeline to perform valve upgrades.",
            formalExampleTranslation = "ستقوم فرق الصيانة بإغلاق خط أنابيب المياه الرئيسي لإجراء ترقيات الصمامات.",
            informalMeaning = "إطفاء الأنوار قبل النوم، أو الانزعاج من سلوك شخص وقح.",
            informalExample = "His rude and arrogant attitude really turned off everyone at the dinner.",
            informalExampleTranslation = "سلوكه الفظ والمتغطرس نفّر وأزعج جميع الحاضرين في مأدبة العشاء."
        ),
        PhrasalVerb(
            id = 89,
            verb = "Turn on",
            summaryMeaning = "يشغل جهازاً / ينقلب ضد شخص فجأة / يثير الحماس",
            formalMeaning = "تشغيل وتفعيل التوربينات أو منظومات التدفئة المركزية في المنشأة.",
            formalExample = "Technicians will safely turn on the regional electrical sub-grid after repairs.",
            formalExampleTranslation = "سيقوم الفنيون بتشغيل الشبكة الفرعية للكهرباء الإقليمية بأمان بعد انتهاء الإصلاحات.",
            informalMeaning = "تشغيل التلفاز، أو انقلاب كلب وديع ليهاجم صاحبه فجأة.",
            informalExample = "Could you turn on the air conditioner? It's burning hot in here.",
            informalExampleTranslation = "هل يمكنك تشغيل مكيف الهواء؟ الجو حار ولا يطاق في الداخل هنا."
        ),
        PhrasalVerb(
            id = 90,
            verb = "Turn out",
            summaryMeaning = "يتضح وينكشف في النهاية / يُنتج سلعاً / يحضر جمهور",
            formalMeaning = "حضور الناخبين للتصويت أو الحصيلة الإنتاجية لمصانع التصنيع.",
            formalExample = "Voter participation turned out to be unprecedentedly high during the general election.",
            formalExampleTranslation = "اتضح أن نسبة إقبال ومشاركة الناخبين كانت مرتفعة بشكل غير مسبوق في الانتخابات.",
            informalMeaning = "اكتشاف أن الأمر كان مختلفاً تماماً عما ظننت.",
            informalExample = "I was worried about the interview, but it turned out to be surprisingly easy!",
            informalExampleTranslation = "كنت قلقاً جداً بشأن المقابلة، لكن اتضح في النهاية أنها كانت سهلة للغاية!"
        ),
        PhrasalVerb(
            id = 91,
            verb = "Turn up",
            summaryMeaning = "يرفع الصوت / يظهر ويعثر عليه صدفة بعد فقدان",
            formalMeaning = "زيادة وتيرة التحريات القضائية أو رفع وتيرة الإنتاج الصناعي.",
            formalExample = "Auditors turned up several previously undisclosed accounts during their forensic review.",
            formalExampleTranslation = "كشف المدققون وتوصلوا إلى عدة حسابات غير معلنة أثناء مراجعتهم الجنائية.",
            informalMeaning = "العثور على المفاتيح الضائعة فجأة، أو رفع صوت الموسيقى.",
            informalExample = "Turn up that song! It's my absolute favorite track on the album!",
            informalExampleTranslation = "ارفع صوت تلك الأغنية! إنها الأغنية المفضلة لدي على الإطلاق في هذا الألبوم!"
        ),
        PhrasalVerb(
            id = 92,
            verb = "Use up",
            summaryMeaning = "يستهلك الشيء حتى آخر قطرة / يستنفد الموارد",
            formalMeaning = "الاستهلاك الشامل للاحتياطيات المخصصة لبرامج الدعم الحكومي.",
            formalExample = "Disaster relief agencies cautioned that ongoing floods would use up contingency reserves.",
            formalExampleTranslation = "حذرت وكالات الإغاثة من أن الفيضانات المستمرة ستستنفد وتستهلك احتياطيات الطوارئ بالكامل.",
            informalMeaning = "شرب آخر قطرة حليب في الثلاجة دون ترك شيء للآخرين.",
            informalExample = "Who used up all the milk without putting it on the shopping list?",
            informalExampleTranslation = "من استهلك الحليب بالكامل دون كتابته في قائمة مشتريات البقالة؟"
        ),
        PhrasalVerb(
            id = 93,
            verb = "Wake up",
            summaryMeaning = "يستيقظ من النوم / يدرك الخطر ويتنبه للحقيقة",
            formalMeaning = "استيقاظ الوعي العام والمؤسسي لمخاطر تغير المناخ أو التهديدات السيبرانية.",
            formalExample = "Policymakers must wake up to the urgent economic threats posed by cyber warfare.",
            formalExampleTranslation = "يجب على صانعي السياسات التنبه والاستيقاظ للتهديدات الاقتصادية العاجلة للحرب السيبرانية.",
            informalMeaning = "الاستيقاظ على صوت المنبه المزعج في الصباح الباكر.",
            informalExample = "I usually wake up at 6 AM every morning to go for a brisk run.",
            informalExampleTranslation = "أستيقظ عادة في السادسة صباحاً كل يوم للذهاب في جولة ركض منعشة."
        ),
        PhrasalVerb(
            id = 94,
            verb = "Warm up",
            summaryMeaning = "يُسخّن الطعام / يُجري تمارين إحماء / يألف ويصبح ودوداً",
            formalMeaning = "التحسن التدريجي والدفء في العلاقات الدبلوماسية بين دولتين متنافستين.",
            formalExample = "Diplomatic ties began to warm up following fruitful trade concessions by both capitals.",
            formalExampleTranslation = "بدأت الروابط الدبلوماسية تشهد دفئاً وتقارباً إيجابياً في أعقاب تقديم تنازلات تجارية متبادلة.",
            informalMeaning = "تسخين طعام الأمس في الميكروويف أو الإحماء قبل ممارسة الرياضة.",
            informalExample = "Always warm up and stretch your muscles before lifting heavy weights.",
            informalExampleTranslation = "احرص دائماً على الإحماء وإطالة عضلاتك قبل ممارسة رفع الأثقال."
        ),
        PhrasalVerb(
            id = 95,
            verb = "Watch out",
            summaryMeaning = "يحترس وينتبه / يراقب ويحذر من محتال",
            formalMeaning = "الرصد واليقظة التنظيمية المستمرة تجاه المعاملات المالية الاحتيالية.",
            formalExample = "Regulators issued a bulletin advising investors to watch out for predatory crypto schemes.",
            formalExampleTranslation = "أصدر المنظمون نشرة توجيهية تنصح المستثمرين بالحذر واليقظة تجاه مخططات العملات المشفرة الاحتيالية.",
            informalMeaning = "تنبيه صديق لأرضية مبللة زلقة تجنباً للسقوط.",
            informalExample = "Watch out for the wet floor; someone just mopped the hallway.",
            informalExampleTranslation = "احترس وانتبه من الأرضية المبللة؛ لقد قام أحدهم بمسح الممر للتو."
        ),
        PhrasalVerb(
            id = 96,
            verb = "Wear off",
            summaryMeaning = "يزول أثره ومفعوله تدريجياً (دواء أو شعور)",
            formalMeaning = "تلاشي وانقضاء التأثيرات التحفيزية لحزم التيسير النقدي في الاقتصاد.",
            formalExample = "Economists noted that the stimulative impact of the tax rebates began to wear off.",
            formalExampleTranslation = "أشار الاقتصاديون إلى أن الأثر التحفيزي للتخفيضات الضريبية بدأ يتلاشى ويزول تدريجياً.",
            informalMeaning = "زوال مفعول حقنة التخدير عند طبيب الأسنان وبدء الشعور بالألم.",
            informalExample = "The dentist's painkiller is wearing off, and my tooth is starting to ache again.",
            informalExampleTranslation = "مفعول مسكن طبيب الأسنان بدأ يزول، وبدأ ضرسي يؤلمني من جديد."
        ),
        PhrasalVerb(
            id = 97,
            verb = "Wear out",
            summaryMeaning = "يهترئ ويبلى بالاستعمال / يُرهق ويُنهك جسدياً",
            formalMeaning = "الاستهلاك والاهتراء الميكانيكي للمعدات الصناعية الحساسة.",
            formalExample = "High-pressure manufacturing cycles will wear out hydraulic seals over extended operations.",
            formalExampleTranslation = "تؤدي دورات التصنيع عالية الضغط إلى اهتراء وتآكل العوازل الهيدروليكية مع التشغيل المطول.",
            informalMeaning = "الشعور بالتعب والإنهاك الشديد بعد يوم عمل شاق.",
            informalExample = "Chasing after three energetic toddlers all day completely wore me out!",
            informalExampleTranslation = "الركض خلف ثلاثة أطفال مشاغبين طوال اليوم أرهقني وأنكني تماماً!"
        ),
        PhrasalVerb(
            id = 98,
            verb = "Wind up",
            summaryMeaning = "يختتم وينهي / يُصفي شركة / يستفز شخصاً",
            formalMeaning = "التصفية القانونية والحل النهائي لأعمال شركة وإبراء ذمتها المالية.",
            formalExample = "The court-appointed liquidator was tasked to wind up the insolvent corporation affairs.",
            formalExampleTranslation = "كُلّف المصفي القضائي المعين من المحكمة بإنهاء وتصفية كافة أعمال الشركة المفلسة قانونياً.",
            informalMeaning = "استفزاز شخص والمزاح الثقيل معه لإغضابه ('are you winding me up?').",
            informalExample = "Don't listen to him, he's just winding you up for a laugh!",
            informalExampleTranslation = "لا تستمع إليه، فهو فقط يستفزك ويمزح معك ليضحك!"
        ),
        PhrasalVerb(
            id = 99,
            verb = "Wipe out",
            summaryMeaning = "يمحو ويقضي على / يسقط سقوطاً مروعاً",
            formalMeaning = "المحو الكامل للديون السيادية، أو استئصال وباء في حملة تحصين شاملة.",
            formalExample = "The debt-forgiveness treaty helped wipe out billions in unpayable foreign arrears.",
            formalExampleTranslation = "ساعدت معاهدة إسقاط الديون في محو وإلغاء مليارات من المتأخرات الخارجية غير القابلة للسداد.",
            informalMeaning = "السقوط العنيف من على دراجة هوائية أو لوح تزلج.",
            informalExample = "The skateboarder lost his balance on the wet ramp and wiped out hard.",
            informalExampleTranslation = "فقد متزلج اللوح توازنه على المنحدر المبتل وسقط سقوطاً عنيفاً."
        ),
        PhrasalVerb(
            id = 100,
            verb = "Wrap up",
            summaryMeaning = "يختتم بنجاح / يلف هدية / يرتدي ملابس دافئة",
            formalMeaning = "الإنهاء الناجح والإبرام الرسمي للمفاوضات أو العقود القانونية.",
            formalExample = "Diplomatic envoys hope to wrap up free-trade discussions before the summit concludes.",
            formalExampleTranslation = "يأمل المبعوثون الدبلوماسيون في اختتام وإبرام مباحثات التجارة الحرة بنجاح قبل ختام القمة.",
            informalMeaning = "لف هدية عيد ميلاد بشريط جميل، أو ارتداء كنزة صوفية دافئة.",
            informalExample = "It's freezing cold outside, so make sure you wrap up in a warm coat!",
            informalExampleTranslation = "الجو شديد البرودة في الخارج، لذا احرص على ارتداء معطف صوفي دافئ!"
        )
    )

    fun getById(id: Int): PhrasalVerb? {
        return verbs.find { it.id == id }
    }
}
